// Code generated by MockGen. DO NOT EDIT.
// Source: v3/dialer/dialer.go

// Package dialer_mock is a generated GoMock package.
package dialer_mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	dialer "github.com/makesalekz/utils/v3/dialer"
	grpc "google.golang.org/grpc"
)

// MockIDialer is a mock of IDialer interface.
type MockIDialer struct {
	ctrl     *gomock.Controller
	recorder *MockIDialerMockRecorder
}

// MockIDialerMockRecorder is the mock recorder for MockIDialer.
type MockIDialerMockRecorder struct {
	mock *MockIDialer
}

// NewMockIDialer creates a new mock instance.
func NewMockIDialer(ctrl *gomock.Controller) *MockIDialer {
	mock := &MockIDialer{ctrl: ctrl}
	mock.recorder = &MockIDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDialer) EXPECT() *MockIDialerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIDialer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIDialerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIDialer)(nil).Close))
}

// Connect mocks base method.
func (m *MockIDialer) Connect(ctx context.Context) (*grpc.ClientConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(*grpc.ClientConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockIDialerMockRecorder) Connect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockIDialer)(nil).Connect), ctx)
}

// SetEndpoint mocks base method.
func (m *MockIDialer) SetEndpoint(endpointName, endpoint string) dialer.IDialer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEndpoint", endpointName, endpoint)
	ret0, _ := ret[0].(dialer.IDialer)
	return ret0
}

// SetEndpoint indicates an expected call of SetEndpoint.
func (mr *MockIDialerMockRecorder) SetEndpoint(endpointName, endpoint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEndpoint", reflect.TypeOf((*MockIDialer)(nil).SetEndpoint), endpointName, endpoint)
}

// SetTimeout mocks base method.
func (m *MockIDialer) SetTimeout(timeout time.Duration) dialer.IDialer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTimeout", timeout)
	ret0, _ := ret[0].(dialer.IDialer)
	return ret0
}

// SetTimeout indicates an expected call of SetTimeout.
func (mr *MockIDialerMockRecorder) SetTimeout(timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockIDialer)(nil).SetTimeout), timeout)
}
