// Code generated by MockGen. DO NOT EDIT.
// Source: v4/nats/queue.go

// Package queues_mock is a generated GoMock package.
package queues_mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockIQueue is a mock of IQueue interface.
type MockIQueue struct {
	ctrl     *gomock.Controller
	recorder *MockIQueueMockRecorder
}

// MockIQueueMockRecorder is the mock recorder for MockIQueue.
type MockIQueueMockRecorder struct {
	mock *MockIQueue
}

// NewMockIQueue creates a new mock instance.
func NewMockIQueue(ctrl *gomock.Controller) *MockIQueue {
	mock := &MockIQueue{ctrl: ctrl}
	mock.recorder = &MockIQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQueue) EXPECT() *MockIQueueMockRecorder {
	return m.recorder
}

// Pub mocks base method.
func (m *MockIQueue) Pub(data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Pub", data)
}

// Pub indicates an expected call of Pub.
func (mr *MockIQueueMockRecorder) Pub(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pub", reflect.TypeOf((*MockIQueue)(nil).Pub), data)
}

// PubDelayed mocks base method.
func (m *MockIQueue) PubDelayed(data any, notBefore time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PubDelayed", data, notBefore)
}

// PubDelayed indicates an expected call of PubDelayed.
func (mr *MockIQueueMockRecorder) PubDelayed(data, notBefore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PubDelayed", reflect.TypeOf((*MockIQueue)(nil).PubDelayed), data, notBefore)
}
