// Code generated by MockGen. DO NOT EDIT.
// Source: v4/nats/queue_manager.go

// Package queues_mock is a generated GoMock package.
package queues_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
	nats "github.com/makesalekz/utils/v4/nats"
)

// MockIQueueManager is a mock of IQueueManager interface.
type MockIQueueManager struct {
	ctrl     *gomock.Controller
	recorder *MockIQueueManagerMockRecorder
}

// MockIQueueManagerMockRecorder is the mock recorder for MockIQueueManager.
type MockIQueueManagerMockRecorder struct {
	mock *MockIQueueManager
}

// NewMockIQueueManager creates a new mock instance.
func NewMockIQueueManager(ctrl *gomock.Controller) *MockIQueueManager {
	mock := &MockIQueueManager{ctrl: ctrl}
	mock.recorder = &MockIQueueManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQueueManager) EXPECT() *MockIQueueManagerMockRecorder {
	return m.recorder
}

// AddConsumer mocks base method.
func (m *MockIQueueManager) AddConsumer(queueName string, handler func(context.Context, jetstream.Msg) bool, opts ...nats.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{queueName, handler}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddConsumer", varargs...)
}

// AddConsumer indicates an expected call of AddConsumer.
func (mr *MockIQueueManagerMockRecorder) AddConsumer(queueName, handler interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{queueName, handler}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConsumer", reflect.TypeOf((*MockIQueueManager)(nil).AddConsumer), varargs...)
}

// AddRemoteConsumer mocks base method.
func (m *MockIQueueManager) AddRemoteConsumer(appName, queueName string, handler func(context.Context, jetstream.Msg) bool, opts ...nats.Option) {
	m.ctrl.T.Helper()
	varargs := []interface{}{appName, queueName, handler}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddRemoteConsumer", varargs...)
}

// AddRemoteConsumer indicates an expected call of AddRemoteConsumer.
func (mr *MockIQueueManagerMockRecorder) AddRemoteConsumer(appName, queueName, handler interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{appName, queueName, handler}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemoteConsumer", reflect.TypeOf((*MockIQueueManager)(nil).AddRemoteConsumer), varargs...)
}

// GetLocal mocks base method.
func (m *MockIQueueManager) GetLocal(name string) nats.IQueue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocal", name)
	ret0, _ := ret[0].(nats.IQueue)
	return ret0
}

// GetLocal indicates an expected call of GetLocal.
func (mr *MockIQueueManagerMockRecorder) GetLocal(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocal", reflect.TypeOf((*MockIQueueManager)(nil).GetLocal), name)
}

// GetRemote mocks base method.
func (m *MockIQueueManager) GetRemote(subj string) nats.IQueue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemote", subj)
	ret0, _ := ret[0].(nats.IQueue)
	return ret0
}

// GetRemote indicates an expected call of GetRemote.
func (mr *MockIQueueManagerMockRecorder) GetRemote(subj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemote", reflect.TypeOf((*MockIQueueManager)(nil).GetRemote), subj)
}
