// Code generated by MockGen. DO NOT EDIT.
// Source: v4/jwt/claims.go

// Package jwt_mock is a generated GoMock package.
package jwt_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITenantClaims is a mock of ITenantClaims interface.
type MockITenantClaims struct {
	ctrl     *gomock.Controller
	recorder *MockITenantClaimsMockRecorder
}

// MockITenantClaimsMockRecorder is the mock recorder for MockITenantClaims.
type MockITenantClaimsMockRecorder struct {
	mock *MockITenantClaims
}

// NewMockITenantClaims creates a new mock instance.
func NewMockITenantClaims(ctrl *gomock.Controller) *MockITenantClaims {
	mock := &MockITenantClaims{ctrl: ctrl}
	mock.recorder = &MockITenantClaimsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITenantClaims) EXPECT() *MockITenantClaimsMockRecorder {
	return m.recorder
}

// GetIdentities mocks base method.
func (m *MockITenantClaims) GetIdentities() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentities")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetIdentities indicates an expected call of GetIdentities.
func (mr *MockITenantClaimsMockRecorder) GetIdentities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentities", reflect.TypeOf((*MockITenantClaims)(nil).GetIdentities))
}

// GetTenantId mocks base method.
func (m *MockITenantClaims) GetTenantId() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantId")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetTenantId indicates an expected call of GetTenantId.
func (mr *MockITenantClaimsMockRecorder) GetTenantId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantId", reflect.TypeOf((*MockITenantClaims)(nil).GetTenantId))
}

// GetUserId mocks base method.
func (m *MockITenantClaims) GetUserId() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserId")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetUserId indicates an expected call of GetUserId.
func (mr *MockITenantClaimsMockRecorder) GetUserId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserId", reflect.TypeOf((*MockITenantClaims)(nil).GetUserId))
}

// IsUserRequest mocks base method.
func (m *MockITenantClaims) IsUserRequest() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserRequest")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserRequest indicates an expected call of IsUserRequest.
func (mr *MockITenantClaimsMockRecorder) IsUserRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserRequest", reflect.TypeOf((*MockITenantClaims)(nil).IsUserRequest))
}

// IsUserTenantRequest mocks base method.
func (m *MockITenantClaims) IsUserTenantRequest() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserTenantRequest")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserTenantRequest indicates an expected call of IsUserTenantRequest.
func (mr *MockITenantClaimsMockRecorder) IsUserTenantRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserTenantRequest", reflect.TypeOf((*MockITenantClaims)(nil).IsUserTenantRequest))
}
