// Code generated by MockGen. DO NOT EDIT.
// Source: v4/jwt/processor.go

// Package jwt_mock is a generated GoMock package.
package jwt_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jwt "gitlab.calendaria.team/services/utils/v4/jwt"
)

// MockIJwtProcessor is a mock of IJwtProcessor interface.
type MockIJwtProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockIJwtProcessorMockRecorder
}

// MockIJwtProcessorMockRecorder is the mock recorder for MockIJwtProcessor.
type MockIJwtProcessorMockRecorder struct {
	mock *MockIJwtProcessor
}

// NewMockIJwtProcessor creates a new mock instance.
func NewMockIJwtProcessor(ctrl *gomock.Controller) *MockIJwtProcessor {
	mock := &MockIJwtProcessor{ctrl: ctrl}
	mock.recorder = &MockIJwtProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJwtProcessor) EXPECT() *MockIJwtProcessorMockRecorder {
	return m.recorder
}

// GetClaimsFromContext mocks base method.
func (m *MockIJwtProcessor) GetClaimsFromContext(ctx context.Context) (jwt.ITenantClaims, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaimsFromContext", ctx)
	ret0, _ := ret[0].(jwt.ITenantClaims)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClaimsFromContext indicates an expected call of GetClaimsFromContext.
func (mr *MockIJwtProcessorMockRecorder) GetClaimsFromContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaimsFromContext", reflect.TypeOf((*MockIJwtProcessor)(nil).GetClaimsFromContext), ctx)
}

// GetSecret mocks base method.
func (m *MockIJwtProcessor) GetSecret() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockIJwtProcessorMockRecorder) GetSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockIJwtProcessor)(nil).GetSecret))
}

// GetUserIdFromContext mocks base method.
func (m *MockIJwtProcessor) GetUserIdFromContext(ctx context.Context) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdFromContext", ctx)
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetUserIdFromContext indicates an expected call of GetUserIdFromContext.
func (mr *MockIJwtProcessorMockRecorder) GetUserIdFromContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdFromContext", reflect.TypeOf((*MockIJwtProcessor)(nil).GetUserIdFromContext), ctx)
}
