// Code generated by MockGen. DO NOT EDIT.
// Source: v4/config/config.go

// Package config_mock is a generated GoMock package.
package config_mock

import (
	context "context"
	reflect "reflect"

	registry "github.com/go-kratos/consul/registry"
	gomock "github.com/golang/mock/gomock"
	api "github.com/hashicorp/vault/api"
)

// MockIConfig is a mock of IConfig interface.
type MockIConfig struct {
	ctrl     *gomock.Controller
	recorder *MockIConfigMockRecorder
}

// MockIConfigMockRecorder is the mock recorder for MockIConfig.
type MockIConfigMockRecorder struct {
	mock *MockIConfig
}

// NewMockIConfig creates a new mock instance.
func NewMockIConfig(ctrl *gomock.Controller) *MockIConfig {
	mock := &MockIConfig{ctrl: ctrl}
	mock.recorder = &MockIConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConfig) EXPECT() *MockIConfigMockRecorder {
	return m.recorder
}

// GetAppName mocks base method.
func (m *MockIConfig) GetAppName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAppName indicates an expected call of GetAppName.
func (mr *MockIConfigMockRecorder) GetAppName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppName", reflect.TypeOf((*MockIConfig)(nil).GetAppName))
}

// GetRegistry mocks base method.
func (m *MockIConfig) GetRegistry() *registry.Registry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistry")
	ret0, _ := ret[0].(*registry.Registry)
	return ret0
}

// GetRegistry indicates an expected call of GetRegistry.
func (mr *MockIConfigMockRecorder) GetRegistry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistry", reflect.TypeOf((*MockIConfig)(nil).GetRegistry))
}

// GetValue mocks base method.
func (m *MockIConfig) GetValue(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockIConfigMockRecorder) GetValue(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockIConfig)(nil).GetValue), key)
}

// GetVault mocks base method.
func (m *MockIConfig) GetVault(ctx context.Context) (*api.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVault", ctx)
	ret0, _ := ret[0].(*api.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVault indicates an expected call of GetVault.
func (mr *MockIConfigMockRecorder) GetVault(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVault", reflect.TypeOf((*MockIConfig)(nil).GetVault), ctx)
}

// ReadGlobalSecretsFor mocks base method.
func (m *MockIConfig) ReadGlobalSecretsFor(ctx context.Context, subpath string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadGlobalSecretsFor", ctx, subpath)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadGlobalSecretsFor indicates an expected call of ReadGlobalSecretsFor.
func (mr *MockIConfigMockRecorder) ReadGlobalSecretsFor(ctx, subpath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadGlobalSecretsFor", reflect.TypeOf((*MockIConfig)(nil).ReadGlobalSecretsFor), ctx, subpath)
}

// ReadJwt mocks base method.
func (m *MockIConfig) ReadJwt(ctx context.Context, app string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadJwt", ctx, app)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadJwt indicates an expected call of ReadJwt.
func (mr *MockIConfigMockRecorder) ReadJwt(ctx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadJwt", reflect.TypeOf((*MockIConfig)(nil).ReadJwt), ctx, app)
}

// ReadSecretsFor mocks base method.
func (m *MockIConfig) ReadSecretsFor(ctx context.Context, subpath string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSecretsFor", ctx, subpath)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSecretsFor indicates an expected call of ReadSecretsFor.
func (mr *MockIConfigMockRecorder) ReadSecretsFor(ctx, subpath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSecretsFor", reflect.TypeOf((*MockIConfig)(nil).ReadSecretsFor), ctx, subpath)
}
