// Code generated by MockGen. DO NOT EDIT.
// Source: v4/badge/badge.go

// Package badge_mock is a generated GoMock package.
package badge_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	struc "gitlab.calendaria.team/services/utils/v2/struc"
)

// MockIBadgeClient is a mock of IBadgeClient interface.
type MockIBadgeClient struct {
	ctrl     *gomock.Controller
	recorder *MockIBadgeClientMockRecorder
}

// MockIBadgeClientMockRecorder is the mock recorder for MockIBadgeClient.
type MockIBadgeClientMockRecorder struct {
	mock *MockIBadgeClient
}

// NewMockIBadgeClient creates a new mock instance.
func NewMockIBadgeClient(ctrl *gomock.Controller) *MockIBadgeClient {
	mock := &MockIBadgeClient{ctrl: ctrl}
	mock.recorder = &MockIBadgeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBadgeClient) EXPECT() *MockIBadgeClientMockRecorder {
	return m.recorder
}

// DecrementBadge mocks base method.
func (m *MockIBadgeClient) DecrementBadge(ctx context.Context, userID int64, badgeType struc.NotificationType, count int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementBadge", ctx, userID, badgeType, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementBadge indicates an expected call of DecrementBadge.
func (mr *MockIBadgeClientMockRecorder) DecrementBadge(ctx, userID, badgeType, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBadge", reflect.TypeOf((*MockIBadgeClient)(nil).DecrementBadge), ctx, userID, badgeType, count)
}

// GetBadges mocks base method.
func (m *MockIBadgeClient) GetBadges(ctx context.Context, userID int64) (map[struc.NotificationType]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBadges", ctx, userID)
	ret0, _ := ret[0].(map[struc.NotificationType]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBadges indicates an expected call of GetBadges.
func (mr *MockIBadgeClientMockRecorder) GetBadges(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBadges", reflect.TypeOf((*MockIBadgeClient)(nil).GetBadges), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockIBadgeClient) GetUsers(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockIBadgeClientMockRecorder) GetUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockIBadgeClient)(nil).GetUsers), ctx)
}

// IncrementBadge mocks base method.
func (m *MockIBadgeClient) IncrementBadge(ctx context.Context, userID int64, badgeType struc.NotificationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementBadge", ctx, userID, badgeType)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementBadge indicates an expected call of IncrementBadge.
func (mr *MockIBadgeClientMockRecorder) IncrementBadge(ctx, userID, badgeType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBadge", reflect.TypeOf((*MockIBadgeClient)(nil).IncrementBadge), ctx, userID, badgeType)
}

// SetBadges mocks base method.
func (m *MockIBadgeClient) SetBadges(ctx context.Context, userID int64, badges map[struc.NotificationType]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBadges", ctx, userID, badges)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBadges indicates an expected call of SetBadges.
func (mr *MockIBadgeClientMockRecorder) SetBadges(ctx, userID, badges interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBadges", reflect.TypeOf((*MockIBadgeClient)(nil).SetBadges), ctx, userID, badges)
}
