// Code generated by MockGen. DO NOT EDIT.
// Source: v2/nats/queues.go

// Package nats_mock is a generated GoMock package.
package nats_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
	nats "gitlab.calendaria.team/services/utils/v2/nats"
)

// MockIQueue is a mock of IQueue interface.
type MockIQueue struct {
	ctrl     *gomock.Controller
	recorder *MockIQueueMockRecorder
}

// MockIQueueMockRecorder is the mock recorder for MockIQueue.
type MockIQueueMockRecorder struct {
	mock *MockIQueue
}

// NewMockIQueue creates a new mock instance.
func NewMockIQueue(ctrl *gomock.Controller) *MockIQueue {
	mock := &MockIQueue{ctrl: ctrl}
	mock.recorder = &MockIQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQueue) EXPECT() *MockIQueueMockRecorder {
	return m.recorder
}

// Pub mocks base method.
func (m *MockIQueue) Pub(data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Pub", data)
}

// Pub indicates an expected call of Pub.
func (mr *MockIQueueMockRecorder) Pub(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pub", reflect.TypeOf((*MockIQueue)(nil).Pub), data)
}

// MockIQueueManager is a mock of IQueueManager interface.
type MockIQueueManager struct {
	ctrl     *gomock.Controller
	recorder *MockIQueueManagerMockRecorder
}

// MockIQueueManagerMockRecorder is the mock recorder for MockIQueueManager.
type MockIQueueManagerMockRecorder struct {
	mock *MockIQueueManager
}

// NewMockIQueueManager creates a new mock instance.
func NewMockIQueueManager(ctrl *gomock.Controller) *MockIQueueManager {
	mock := &MockIQueueManager{ctrl: ctrl}
	mock.recorder = &MockIQueueManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQueueManager) EXPECT() *MockIQueueManagerMockRecorder {
	return m.recorder
}

// AddConsumer mocks base method.
func (m *MockIQueueManager) AddConsumer(queueName string, handler func(context.Context, jetstream.Msg) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddConsumer", queueName, handler)
}

// AddConsumer indicates an expected call of AddConsumer.
func (mr *MockIQueueManagerMockRecorder) AddConsumer(queueName, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConsumer", reflect.TypeOf((*MockIQueueManager)(nil).AddConsumer), queueName, handler)
}

// AddRemoteConsumer mocks base method.
func (m *MockIQueueManager) AddRemoteConsumer(appName, queueName string, handler func(context.Context, jetstream.Msg) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRemoteConsumer", appName, queueName, handler)
}

// AddRemoteConsumer indicates an expected call of AddRemoteConsumer.
func (mr *MockIQueueManagerMockRecorder) AddRemoteConsumer(appName, queueName, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemoteConsumer", reflect.TypeOf((*MockIQueueManager)(nil).AddRemoteConsumer), appName, queueName, handler)
}

// GetLocal mocks base method.
func (m *MockIQueueManager) GetLocal(name string) nats.IQueue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocal", name)
	ret0, _ := ret[0].(nats.IQueue)
	return ret0
}

// GetLocal indicates an expected call of GetLocal.
func (mr *MockIQueueManagerMockRecorder) GetLocal(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocal", reflect.TypeOf((*MockIQueueManager)(nil).GetLocal), name)
}

// GetRemote mocks base method.
func (m *MockIQueueManager) GetRemote(subj string) nats.IQueue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemote", subj)
	ret0, _ := ret[0].(nats.IQueue)
	return ret0
}

// GetRemote indicates an expected call of GetRemote.
func (mr *MockIQueueManagerMockRecorder) GetRemote(subj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemote", reflect.TypeOf((*MockIQueueManager)(nil).GetRemote), subj)
}
