// Code generated by MockGen. DO NOT EDIT.
// Source: v2/dialer/dialer_manager.go

// Package dialer_mock is a generated GoMock package.
package dialer_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dialer "github.com/makesalekz/utils/v2/dialer"
)

// MockIDialerManager is a mock of IDialerManager interface.
type MockIDialerManager struct {
	ctrl     *gomock.Controller
	recorder *MockIDialerManagerMockRecorder
}

// MockIDialerManagerMockRecorder is the mock recorder for MockIDialerManager.
type MockIDialerManagerMockRecorder struct {
	mock *MockIDialerManager
}

// NewMockIDialerManager creates a new mock instance.
func NewMockIDialerManager(ctrl *gomock.Controller) *MockIDialerManager {
	mock := &MockIDialerManager{ctrl: ctrl}
	mock.recorder = &MockIDialerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDialerManager) EXPECT() *MockIDialerManagerMockRecorder {
	return m.recorder
}

// NewServiceDialer mocks base method.
func (m *MockIDialerManager) NewServiceDialer(endpointName, endpoint string) (dialer.IDialer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewServiceDialer", endpointName, endpoint)
	ret0, _ := ret[0].(dialer.IDialer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewServiceDialer indicates an expected call of NewServiceDialer.
func (mr *MockIDialerManagerMockRecorder) NewServiceDialer(endpointName, endpoint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewServiceDialer", reflect.TypeOf((*MockIDialerManager)(nil).NewServiceDialer), endpointName, endpoint)
}
