// Code generated by MockGen. DO NOT EDIT.
// Source: v3/jwt/secrets.go

// Package jwt_mock is a generated GoMock package.
package jwt_mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIJwtSecret is a mock of IJwtSecret interface.
type MockIJwtSecret struct {
	ctrl     *gomock.Controller
	recorder *MockIJwtSecretMockRecorder
}

// MockIJwtSecretMockRecorder is the mock recorder for MockIJwtSecret.
type MockIJwtSecretMockRecorder struct {
	mock *MockIJwtSecret
}

// NewMockIJwtSecret creates a new mock instance.
func NewMockIJwtSecret(ctrl *gomock.Controller) *MockIJwtSecret {
	mock := &MockIJwtSecret{ctrl: ctrl}
	mock.recorder = &MockIJwtSecretMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJwtSecret) EXPECT() *MockIJwtSecretMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIJwtSecret) Get() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockIJwtSecretMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIJwtSecret)(nil).Get))
}
